/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    /** Home Page */
    get: operations["home_page__get"];
  };
  "/livechart/anime/{anime_id}": {
    /** Live Anime */
    get: operations["live_anime_livechart_anime__anime_id__get"];
  };
  "/livechart/schedule": {
    /** Live Anime Schedule */
    get: operations["live_anime_schedule_livechart_schedule_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AnimeData */
    AnimeData: {
      /** Livechart Id */
      livechart_id: string;
      /** Romaji Title */
      romaji_title: string;
      /** English Title */
      english_title: string;
      /** Native Title */
      native_title: string;
      /** Alternate Titles */
      alternate_titles: string[];
      /** Premiere Timestamp */
      premiere_timestamp: number;
      /** Main Title */
      main_title: string;
      /** Genres */
      genres: string[];
      /** Studio */
      studio: string[];
      /** Premiere Date */
      premiere_date: string;
      /** Synopsis */
      synopsis: string;
      /** Anime Source */
      anime_source: string;
      /** Anime Episodes */
      anime_episodes: string;
      anilist: components["schemas"]["AnimeLink"];
      mal: components["schemas"]["AnimeLink"];
      anidb: components["schemas"]["AnimeLink"];
      animeplanet: components["schemas"]["AnimeLink"];
      anisearch: components["schemas"]["AnimeLink"];
      kitsu: components["schemas"]["AnimeLink"];
      website: components["schemas"]["AnimeLink"];
      /** Posters */
      posters: string[];
    };
    /** AnimeInfo */
    AnimeInfo: {
      /** Posters */
      posters: string[];
      /** Rating */
      rating: string;
      titles: components["schemas"]["AnimeTitles"];
      /** Premiere */
      premiere: string;
      /** Season */
      season: string;
      /** Website */
      website: string;
      /** Status */
      status: string;
      /** Anime Format */
      anime_format?: string | null;
      /** Source */
      source?: string | null;
      /** Episodes */
      episodes?: string | null;
      /** Run Time */
      run_time?: string | null;
      /** Description */
      description?: string | null;
      /** Studios */
      studios: string[];
      /** Tags */
      tags: string[];
      /** Anilist Id */
      anilist_id?: string | null;
      /** Mal Id */
      mal_id?: string | null;
      /** Anidb Id */
      anidb_id?: string | null;
      /** Animeplanet Id */
      animeplanet_id?: string | null;
      /** Anisearch Id */
      anisearch_id?: string | null;
      /** Kitsu Id */
      kitsu_id?: string | null;
    };
    /** AnimeLink */
    AnimeLink: {
      /** Id */
      id: string | null;
      /** Url */
      url: string | null;
    };
    /** AnimeTitles */
    AnimeTitles: {
      /** Romaji */
      romaji: string;
      /** English */
      english: string;
      /** Native */
      native: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Home Page */
  home_page__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Live Anime */
  live_anime_livechart_anime__anime_id__get: {
    parameters: {
      path: {
        anime_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AnimeInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Live Anime Schedule */
  live_anime_schedule_livechart_schedule_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<
            string,
            components["schemas"]["AnimeData"][]
          >;
        };
      };
    };
  };
}
