/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    /** Home Page */
    get: operations["home_page__get"];
  };
  "/livechart/anime/{anime_id}": {
    /** Live Anime */
    get: operations["live_anime_livechart_anime__anime_id__get"];
  };
  "/livechart/schedule": {
    /** Live Anime Schedule */
    get: operations["live_anime_schedule_livechart_schedule_get"];
  };
  "/gogoanime/search": {
    /** Search */
    get: operations["search_gogoanime_search_get"];
  };
  "/gogoanime/anime/{anime_id}": {
    /** Getanimeinfo */
    get: operations["getAnimeInfo_gogoanime_anime__anime_id__get"];
  };
  "/gogoanime/watch/{episode_id}": {
    /** Getanimeepisode */
    get: operations["getAnimeEpisode_gogoanime_watch__episode_id__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** GogoAnimeEpisode */
    GogoAnimeEpisode: {
      /** Id */
      id: string;
      /** Number */
      number: number;
      /** Url */
      url: string;
    };
    /** GogoAnimeGogoCdn */
    GogoAnimeGogoCdn: {
      headers: components["schemas"]["GogoAnimeGogoCdnHeaders"];
      /** Sources */
      sources: components["schemas"]["GogoAnimeGogoCdnUrl"][];
      /** Download */
      download: string;
    };
    /** GogoAnimeGogoCdnHeaders */
    GogoAnimeGogoCdnHeaders: {
      /** Referer */
      referer: string;
    };
    /** GogoAnimeGogoCdnUrl */
    GogoAnimeGogoCdnUrl: {
      /** Url */
      url: string;
      /** Ism3U8 */
      isM3U8: boolean;
      /** Quality */
      quality: string;
    };
    /** GogoAnimeInfo */
    GogoAnimeInfo: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Url */
      url: string;
      /** Genres */
      genres: string[];
      /** Totalepisodes */
      totalEpisodes: number;
      /** Image */
      image: string;
      /** Releasedate */
      releaseDate: string;
      /** Description */
      description: string;
      /** Subordub */
      subOrDub: string;
      /** Type */
      type: string;
      /** Status */
      status: string;
      /** Othername */
      otherName: string;
      /** Episodes */
      episodes: components["schemas"]["GogoAnimeEpisode"][];
    };
    /** GogoAnimeSearch */
    GogoAnimeSearch: {
      /** Currentpage */
      currentPage: number;
      /** Hasnextpage */
      hasNextPage: boolean;
      /** Results */
      results: components["schemas"]["GogoAnimeSearchResult"][];
    };
    /** GogoAnimeSearchResult */
    GogoAnimeSearchResult: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Url */
      url: string;
      /** Image */
      image: string;
      /** Releasedate */
      releaseDate: string;
      /** Subordub */
      subOrDub: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LiveChartAnimeData */
    LiveChartAnimeData: {
      /** Livechart Id */
      livechart_id: string;
      /** Romaji Title */
      romaji_title: string;
      /** English Title */
      english_title: string;
      /** Native Title */
      native_title: string;
      /** Alternate Titles */
      alternate_titles: string[];
      /** Premiere Timestamp */
      premiere_timestamp: number;
      /** Episode */
      episode: string;
      /** Main Title */
      main_title: string;
      /** Genres */
      genres: string[];
      /** Studio */
      studio: string[];
      /** Premiere Date */
      premiere_date: string;
      /** Synopsis */
      synopsis: string;
      /** Anime Source */
      anime_source: string;
      /** Anime Episodes */
      anime_episodes: string;
      anilist: components["schemas"]["LiveChartAnimeLink"];
      mal: components["schemas"]["LiveChartAnimeLink"];
      anidb: components["schemas"]["LiveChartAnimeLink"];
      animeplanet: components["schemas"]["LiveChartAnimeLink"];
      anisearch: components["schemas"]["LiveChartAnimeLink"];
      kitsu: components["schemas"]["LiveChartAnimeLink"];
      website: components["schemas"]["LiveChartAnimeLink"];
      /** Posters */
      posters: string[];
    };
    /** LiveChartAnimeInfo */
    LiveChartAnimeInfo: {
      /** Posters */
      posters: string[];
      /** Rating */
      rating: string;
      titles: components["schemas"]["LiveChartAnimeTitles"];
      /** Premiere */
      premiere: string;
      /** Season */
      season: string;
      /** Website */
      website: string;
      /** Status */
      status: string;
      /** Anime Format */
      anime_format?: string | null;
      /** Source */
      source?: string | null;
      /** Episodes */
      episodes?: string | null;
      /** Run Time */
      run_time?: string | null;
      /** Description */
      description?: string | null;
      /** Studios */
      studios: string[];
      /** Tags */
      tags: string[];
      /** Anilist Id */
      anilist_id?: string | null;
      /** Mal Id */
      mal_id?: string | null;
      /** Anidb Id */
      anidb_id?: string | null;
      /** Animeplanet Id */
      animeplanet_id?: string | null;
      /** Anisearch Id */
      anisearch_id?: string | null;
      /** Kitsu Id */
      kitsu_id?: string | null;
    };
    /** LiveChartAnimeLink */
    LiveChartAnimeLink: {
      /** Id */
      id: string | null;
      /** Url */
      url: string | null;
    };
    /** LiveChartAnimeTitles */
    LiveChartAnimeTitles: {
      /** Romaji */
      romaji: string;
      /** English */
      english: string;
      /** Native */
      native: string;
    };
    /**
     * StreamingServers
     * @enum {string}
     */
    StreamingServers:
      | "asianload"
      | "gogocdn"
      | "streamsb"
      | "mixdrop"
      | "mp4upload"
      | "upcloud"
      | "vidcloud"
      | "streamtape"
      | "vizcloud"
      | "mycloud"
      | "filemoon"
      | "vidstreaming"
      | "smashystream"
      | "streamhub"
      | "streamwish"
      | "vidmoly";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Home Page */
  home_page__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Live Anime */
  live_anime_livechart_anime__anime_id__get: {
    parameters: {
      path: {
        anime_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LiveChartAnimeInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Live Anime Schedule */
  live_anime_schedule_livechart_schedule_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<
            string,
            components["schemas"]["LiveChartAnimeData"][]
          >;
        };
      };
    };
  };
  /** Search */
  search_gogoanime_search_get: {
    parameters: {
      query: {
        query: string;
        page?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GogoAnimeSearch"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Getanimeinfo */
  getAnimeInfo_gogoanime_anime__anime_id__get: {
    parameters: {
      path: {
        anime_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GogoAnimeInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Getanimeepisode */
  getAnimeEpisode_gogoanime_watch__episode_id__get: {
    parameters: {
      query?: {
        server?: components["schemas"]["StreamingServers"];
      };
      path: {
        episode_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GogoAnimeGogoCdn"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
